name: Node.js CI

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

concurrency:
  group: nalanda-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_OWNER: ${{ secrets.GH_OWNER }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Run test "${{ matrix.test-kind }}"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - run: lint
        run: pnpm lint
      - name: test
        run: pnpm test
      - name: buid
        run: pnpm build

