name: Node.js CI

on:
  push:
    branches: [main, dev, alpha]
  pull_request:
    branches: [main, dev, alpha]

concurrency:
  group: nalanda-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Run test "${{ matrix.test-kind }}"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: test
        run: pnpm test
      - name: buid
        run: pnpm build
      - name: prep release
        run: pnpm node ./scripts/prepare-release.js
      - run: pnpx semantic-release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
